@startuml

left to right direction

card 系统配置

frame 管理后端 {
card 注册账号
card 生成鉴权令牌
card 创建产品项
}

card 系统集成

frame SDK {
card 开发文档
card 库文件
card 初始化接口
}

预处理 --> 系统配置
预处理 --> 系统集成

系统配置 --> 管理后端

'系统配置 --> 注册账号
'系统配置 --> 生成鉴权令牌
'系统配置 --> 创建产品项

系统集成 --> SDK

注册账号 --> 生成鉴权令牌
注册账号 --> 创建产品项

'系统集成 --> 开发文档
'系统集成 --> 库文件
库文件 --> 初始化接口

'生成鉴权令牌 --> 初始化接口 : 鉴权令牌传参
'创建产品项 --> 初始化接口 : 产品信息传参

@enduml
