@startuml
'https://plantuml.com/use-case-diagram

接口前端 -> 数据捕获: 初始化
数据捕获 -> 数据存储: 保存崩溃异常信息
接口前端 -> 数据存储: 保存自定义信息
数据存储 -> 数据上报: 提供崩溃异常信息
数据上报 -> 数据存储: 请求删除已上报数据
接口前端 -> 数据上报: 提供鉴权令牌
数据上报 -> 管理后端 :向管理后台上报
@enduml